### PR TITLE
Remove examples from the content policy.

### PR DESCRIPTION
**Pull request by iangcarroll**
Not done yet.

### CODE REVIEW

**Comment by gsingh93** [comment]
Thanks for working on this Ian.

Please rebase on my original branch to pick up some changes.

When you're rewriting the sections, try to address points 2 and 3 [here](https://github.com/wearehx/policies/pull/2#issuecomment-170134545), which haven't been addressed yet.

**Comment by gsingh93** [comment]
I just realized today that checking whether an image is a repost might actually be kind of hard. It's not easy to search for those things in facebook if the image is hosted on a different link.

**Comment by iangcarroll** [comment]
It's in a rough form now, and there are some things I want to fix, but comments are welcome at this point. // @gsingh93

**Comment by gsingh93** [comment]
Any more updates @iangcarroll

**Comment by iangcarroll** [comment]
I'd like feedback on the fact I removed the 'good' section. Other than that I'll look it over tonight and see what needs to be added, if anything.

**Comment by frankcash** [comment]
LGTM  at the next meeting :+1:

**Comment by gsingh93** [comment]
Can you add something that clarifies that while "bad" posts are ultimately subjective, admins have the authority to make a final call on a post, even if that post isn't explicitly deemed as bad by the content policy.

Should we specifically address social posts in this document?

**Pull request merged**
