### PR TITLE
Added Content Policy

### PR DESCRIPTION
**Pull request by gsingh93**
[(rendered)](https://github.com/wearehx/policies/blob/content-policy/content-policy.md)

### CODE REVIEW

**Comment by RitwikGupta** [comment]
I say we should get rid of the answers to the examples since it clutters up the policy. Since we just want to show people what kind of things not to post, they can Google to find the answers themselves.

**Comment by zmughal** [comment]
Looks good to me as a first pass. Hasn't changed much since I saw the Google Docs version. :+1:

**Comment by RitwikGupta** [comment]
Would also suggest bolding the TL;DR

**Comment by gsingh93** [comment]
@RitwikGupta, what if we split the list of "what not to post" from the examples of what not post? We would have both sections, but kept separately.

**Comment by RitwikGupta** [comment]
I like that idea!

**Comment by letsgitit** [comment]
So there is absolutely nothing on what happens when you break content policy (aka punishment).

**Comment by gsingh93** [comment]
@letsgitit, that document is coming out tonight (hopefully)

**Comment by AlJohri** [comment]
I'm definitely a +1 on keeping politics in this group. I think a lot of the work we do as computer scientists and software engineers have major political implications which are worth discussing and trying to have an "apolitical" stance is pretty bullshit. Not everyone will be happy with this view though, I'm sure.

**Comment by gsingh93** [comment]
@AlJohri do you think all politics are on topic though? For example, Donald Trump saying something stupid about the internet might be considered relevant, but if he said something about immigration, would that also be relevant (my take is no).

I also think politics in the sense of censorship, NSA spying, net neutrality, etc. is on topic.

**Comment by AlJohri** [comment]
Yeah, I mean Trump said he wanted to close parts of the internet and Kasich declared encryption "the enemy" in tonight's debate :disappointed: which are definitely relevant topics, like you said.

As far as **all** politics, its hard to say....

I'm of the opinion that talking about socioeconomic equality, gender imbalance, the gentrification of SF and all that jazz is pretty relevant especially when it relates to our community / discipline. I also thing Climate Change can be pretty relevant. I remember seeing this article [What can a Technologist do about Climate Change?](http://worrydream.com/ClimateChange/) posted in HH pretty recently which was interesting. I think Seattle allowing Uber driver's to unionize yesterday is super relevant and it'll be interesting to see what this means for the sharing economy as a whole.

But in all honesty there's not that many political posts overall from what I've seen. We can probably check https://github.com/HackathonHackers/data if we care enough, but I think allowing all political posts and seeing what truly gets annoying/unruly from there on might be a decent way to go about things.

What do you think was actually annoying about the political posts? What got people riled up? Seeing opinions differing from their own? (aka "liberal agenda stuffed down their throat")

**Comment by gsingh93** [comment]
I think those topics are all borderline ok, as they all relate to the tech industry in different ways.

I don't remember specific examples, but I do have one example I reported which was related to racism/discrimination: https://www.facebook.com/groups/hackathonhackers/permalink/1129578880430929/

Yes, racism and discrimination are important topics to a lot of people, but HH was not the place to post that article and HX isn't either (IMO). If there's an article about discrimination specifically relating to the tech industry, I'd say that is on topic. (Note that I had a long, heated discussion with the HH mods about this post, and they deemed it to be on topic for HH).

I've seen other examples similar to this come up related to politics, and that's what I'm trying to avoid.

**Comment by letsgitit** [comment]
Do not know where to put this. But I think it is important that there is a balance of power for mods. Much like the united states government, I think there should be 3 branches of 1 or more mods. 1 branch deals with writing, and ammending policy (legislative), one branch for enforcing policy (executive), and a final for any disputes, appeals (judicial).

**Comment by RitwikGupta** [comment]
I think having branches is way too complicated. Remember, it's a Facebook group with a few thousand people, not millions. We don't need that kind of moderation.

**Comment by iangcarroll** [comment]
We should also ban posts asking for nominations/votes, at least outside Meta.

**Comment by letsgitit** [comment]
By branches i just mean balance of power. Like the total mod size could be 3, but each mod could have different powers/responsibilities. No matter the size, it's important to create a system where no one person can exercise  too much power.

**Comment by gsingh93** [comment]
@iangcarroll, I'm not sure whether asking or nominations/votes fits better into HX Meta or the main group. HX Meta is for meta posts about how the group is being run, so questions about content/policy, suggestions, or proposed changes to policies are on topic there. Announcements are off topic there and are on topic for the main group. I feel like asking for nominations fits better with the main group, under "announcements". Of course, the basic reposting rules will apply to these posts.

@letsgitit I share your sentiment about not allowing admins to gain too much power, but I don't think branches will solve that issue. I think what will solve that issue is the transparency that this document is requiring for admins.

**Comment by letsgitit** [comment]
Checks and balances=branches

**Comment by iangcarroll** [comment]
@gsingh93 pointed out the Admin Policy [references deletion](https://github.com/wearehx/policies/blob/admin-policy/admin-policy.md#deletion-of-posts) and I agree in thinking that we should just revert 5645fba and default to the AP instead, possibly modifying it to include a warning before closing threads.

> All other content will be closed.

This is a bit ambiguous; I assume it means something like "All other content violating the Content Policy will be closed."

> You may be banned by violating any of the rules defined in the content policy.

Should certain offenses be marked as bannable?

We should also define "objectionable".

**Comment by gsingh93** [comment]
In order for this PR to land, three things need to happen.

**1. We need to decide what we want to do about jokes/memes**

The three options here are to not allow them at all, allow all jokes/memes, or not jokes/memes as top-level posts and only allow them as comments. I'm leaning towards the last option. (Note that I include things like comic strips under jokes).

I think an exception is if the joke prompts discussion. Example, posting this image would normally not be allowed: http://churchm.ag/wp-content/uploads/2011/12/TheGreatestGift.jpg

However, if the OP wanted to have a discussion about how VR would affect social norms, that would be OK.

**2. Decide how we want to deal with social posts**

Decide whether we really want to not allow social posts like this: https://www.facebook.com/groups/wearehx/permalink/1715379258706592/

On one hand, the post doesn't have any discussion. On the other hand, it's a good list of books to read, and the post had a lot of participation (based on the number of comments). People might find it useful.

One idea would be to allow questions like this if they had some sort of an "intellectual" spin. I.e. talking about books is fine, but asking for a good "coding playlist" would be bad. It's just another way of asking for someone's favorite song, which IMO is not a good topic for HX. Another idea is to allow all of these posts as long as they obey the no reposting rule, but I feel there will be a lot of reposts. If the admins work hard at linking to the older posts and closing reposts, I think they could make this work.

**3. We should make sure we're in agreement about vague posts**

IMO, this is a bad post: https://www.facebook.com/groups/wearehx/permalink/1714221572155694/. We're going to get a lot of these, and I want to make sure we agree that this is a bad post, and ideally draft some response to it and put it in the Content Policy.

Sidenote: Do want to have sections with numbers in this policy? It would make referring to sections easier, but would be a bit more work for me. Also, do we want to separate examples from policy descriptions? There was one comment saying we should, do people agree?

**Comment by iangcarroll** [comment]
Taking into account today's event:
1. I agree, for the most part. If a joke is in a comment, or it is part of a larger post that prompts discussion, it's fine. If the discussion is implied (the joke itself should be followed up with a question prompting the discussion), as we have recently seen, it should not be allowed. I don't think we want to go down the long route of trying to define jokes that provoke questions.
2. I am in favor of posts that provoke helpful, intellectual responses. Things like music playlists are probably not something I'd support, but I also can't think of a way to write a policy that includes books but not coding playlists.
3. I agree the linked post is vague, but I don't want to close them. Messaging the author or posting a comment with a canned response is, imo, a better idea. 

We definitely need numbers and we definitely need to redo the good/bad section to clearly state the good or bad thing and have optional, non-binding examples.

On the specific note of Shane's post today, I would suggest the following:
- We close posts that are off-topic (not that we already don't) that require you to state why they are on-topic, as a guideline.
- We message the author telling them that their post is off-topic when the above happens, but if they convey a valid reason for their post to still be up, the admin should suggest ways to improve the post, and eventually allow it to be posted again.
- We remove the term "hacker culture" and replace it with something else (not sure yet, but it's currently too vague.)

Also, we discussed this via IRC, but for the record the admin policy's section on deletion is currently worded to say that we can close all posts regardless of policy violations.

**Comment by frankcash** [comment]
1.  I think dank maymays should be allowed in a top level post as long as there is an accompanying discussion that is of a certain quality.  
2. In favour of thought provoking/insightful social posts.
3. I agree with @iangcarroll's take on this.

**Comment by gsingh93** [comment]
Regarding jokes, here's a joke which probably won't prompt any discussion but I would be fine with allowing in HX: https://www.facebook.com/groups/wearehx/permalink/1719034745007710/

Now this is entirely my opinion and very subjective, but I find the joke to be funny, from a high quality source (XKCD), relevant to hackers, novel (I haven't seen people make this joke before), and not a repost.

**Comment by gsingh93** [comment]
I tried to update this today, but I was unable to split the examples away from the descriptions of good/bad content. The reason is that concisely describing everything that is on-topic/off-topic is hard, but providing a general description with some examples is much easier. I'm in favor of leaving that format unless anyone else things they can do a better job.

I will get to the other changes though, just not tonight.

**Comment by arirawr** [comment]
Should make meta posts allowed only in HX Meta. They often have many comments and get pushed to the tops of people's newsfeeds.

**Pull request merged**
